stages:
  - test
  - build
  - build-docker
  - deploy
    
test_demo:
  stage: test
  image: node:16.13.1-alpine
  script:
    - echo "testing testing"

.test_react:
  stage: test
  image: node:16.13.1-alpine
  script:
    - cd frontend
    - yarn install
    - yarn run test

.build_react:
  stage: build
  image: node:16.13.1-alpine
  script:
    - cd frontend
    - npm install
    - npm run build

build_django:
  stage: build-docker
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD
  script:
    - docker build -t gerrome/real-estate_backend:1 ./backend
    - docker push gerrome/real-estate_backend:1

.build_vue-nginx:
  stage: build-docker
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD
  script:
    - docker build -t gerrome/real-estate_nginx:1 ./frontend
    - docker push gerrome/real-estate_nginx:1

.deploy_test:
  stage: deploy
  image: ubuntu
  before_script:
    - apt update && apt install -y openssh-client
    - chmod 400 $SSH
    - cat /etc/ssh/sshd_config
  
  script:
    - ssh -o StrictHostKeyChecking=no -i $SSH victor@192.168.56.111 "cd K8s"

