version: "3.3"

services:
    backend:
      image: gerrome/django-react-app_backend:1
    #  build:
    #      context: ./backend
      volumes:
       # - ./backend:/app
        - static_volume:/app/staticfiles/
      ports:
        - 8000:8000
      depends_on:
        - db

    db:
      image: postgres:10.1-alpine
      volumes:
        - ./data/db:/var/lib/postgresql/data
      expose:
        - 5432
      environment:
        - POSTGRES_DB=realest_estate
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres

    client:
      image: gerrome/django-react-app_client:1
    #  build:
    #     context: ./frontend
      env_file: ./.env
      ports:
        - 3000:3000
      volumes:
        - static_volume:/app/staticfiles/
      depends_on:
        - backend

    nginx:
      build:
        context: ./nginx
      ports:
        - "80:80"
      depends_on:
        - client      

    
volumes:
   static_volume: 
